spring:
  application:
    name: desafio-estagio-java

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true